apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: marioberthoud/sif-example:latest   # If you do not provide a <tag>, k8s will use `latest`
          imagePullPolicy: "Always"   # This means the container runtime will pull the image every time the pod is (re-)created. Another possible value is 'IfNotPresent'
          ports:
            - containerPort: 8000     # Exposes a port in a given container to receive traffic
          envFrom:
            - configMapRef:
                name: example-configmap
