apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viz
  template:
    metadata:
      labels:
        app: viz
    spec:
      containers:
        - name: viz
          image: marioberthoud/sif-viz:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: viz-configmap
