apiVersion: v1
kind: Service
metadata:
  name: viz
spec:
  type: NodePort
  ports:
    - name: viz
      port: 9000
      targetPort: 9000
      nodePort: 9000
      protocol: TCP
  selector:
    app: viz
